### ISSUE TITLE
Configuration does not work for blockBytes == beatBytes

### ISSUE THREAD

**Issue by shili2017** [chipsalliance/rocket-chip-inclusive-cache#16]
Hi, current configuration fails when I set blockBytes equal to beatBytes. I believe that this can be solved by making the following modifications, but not sure whether it follows the convention of project. If it looks good, I can start a pull request.

1. `Parameters.scala` [Line 191-192](https://github.com/chipsalliance/rocket-chip-inclusive-cache/blob/main/design/craft/inclusivecache/src/Parameters.scala#L191)
```scala
  val innerBeatBits = offsetBits - log2Ceil(inner.manager.beatBytes)
  val outerBeatBits = offsetBits - log2Ceil(outer.manager.beatBytes)
```
to
```scala
  val innerBeatBits = (offsetBits - log2Ceil(inner.manager.beatBytes)) max 1
  val outerBeatBits = (offsetBits - log2Ceil(outer.manager.beatBytes)) max 1
```

2. `SourceC.scala` [Line 68](https://github.com/chipsalliance/rocket-chip-inclusive-cache/blob/main/design/craft/inclusivecache/src/SourceC.scala#L68)
```scala
  val last = beat.andR
```
to
```scala
  val last = beat === (params.cache.blockBeats - 1).U
```

3. `BankedStore.scala` [Line 126](https://github.com/chipsalliance/rocket-chip-inclusive-cache/blob/main/design/craft/inclusivecache/src/BankedStore.scala#L126)
```scala
    val a = Cat(b.bits.way, b.bits.set, b.bits.beat)
```
to
```scala
    val a = if (params.cache.blockBytes == beatBytes) Cat(b.bits.way, b.bits.set) else Cat(b.bits.way, b.bits.set, b.bits.beat)
```

Thanks!

**Comment by jerryz123** [comment]
Thanks! These changes look reasonable, and a PR would be appreciated.
